### ISSUE TITLE
部署时出现了问题

### ISSUE THREAD

**Issue by na-neko** [Kyomotoi/ATRI#102]
11-15 01:46:21 [SUCCESS] nonebot | NoneBot is initializing...
11-15 01:46:21 [INFO] nonebot | Current Env: prod
ATRI | 11-15 01:46:21 | SUCCESS nonebot >> Succeeded to load plugin "thesaurus" from "ATRI.plugins.thesaurus"
ATRI | 11-15 01:46:21 | SUCCESS nonebot >> Succeeded to load plugin "funny" from "ATRI.plugins.funny"
ATRI | 11-15 01:46:21 | SUCCESS nonebot >> Succeeded to load plugin "polaroid" from "ATRI.plugins.polaroid"
ATRI | 11-15 01:46:22 | SUCCESS nonebot >> Succeeded to load plugin "kimo" from "ATRI.plugins.kimo"
ATRI | 11-15 01:46:22 | SUCCESS nonebot >> Succeeded to load plugin "geoip" from "ATRI.plugins.geoip"
ATRI | 11-15 01:46:22 | SUCCESS nonebot >> Succeeded to load plugin "repo" from "ATRI.plugins.repo"
ATRI | 11-15 01:46:22 | SUCCESS nonebot >> Succeeded to load plugin "auto_tietie" from "ATRI.plugins.auto_tietie"
ATRI | 11-15 01:46:22 | SUCCESS nonebot >> Succeeded to load plugin "setu" from "ATRI.plugins.setu"
ATRI | 11-15 01:46:22 | SUCCESS nonebot >> Succeeded to load plugin "twitter" from "ATRI.plugins.twitter"
ATRI | 11-15 01:46:22 | SUCCESS nonebot >> Succeeded to load plugin "anime_search" from "ATRI.plugins.anime_search"
ATRI | 11-15 01:46:22 | SUCCESS nonebot >> Succeeded to load plugin "broadcast" from "ATRI.plugins.broadcast"
ATRI | 11-15 01:46:22 | SUCCESS nonebot >> Succeeded to load plugin "applet" from "ATRI.plugins.applet"
ATRI | 11-15 01:46:22 | SUCCESS nonebot >> Succeeded to load plugin "util" from "ATRI.plugins.util"
ATRI | 11-15 01:46:22 | SUCCESS nonebot >> Succeeded to load plugin "help" from "ATRI.plugins.help"
ATRI | 11-15 01:46:22 | SUCCESS nonebot >> Succeeded to load plugin "saucenao" from "ATRI.plugins.saucenao"
ATRI | 11-15 01:46:22 | SUCCESS nonebot >> Succeeded to load plugin "essential" from "ATRI.plugins.essential"
ATRI | 11-15 01:46:22 | SUCCESS nonebot >> Succeeded to load plugin "code_runner" from "ATRI.plugins.code_runner"
ATRI | 11-15 01:46:23 | SUCCESS nonebot >> Succeeded to load plugin "bilibili_dynamic" from "ATRI.plugins.bilibili_dynamic"
ATRI | 11-15 01:46:23 | SUCCESS nonebot >> Succeeded to load plugin "manage" from "ATRI.plugins.manage"
ATRI | 11-15 01:46:23 | SUCCESS nonebot >> Succeeded to load plugin "status" from "ATRI.plugins.status"
ATRI | 11-15 01:46:23 | SUCCESS nonebot >> Succeeded to load plugin "rss" from "ATRI.plugins.rss"
ATRI | 11-15 01:46:23 | SUCCESS nonebot >> Succeeded to load plugin "anti_effort" from "ATRI.plugins.anti_effort"
ATRI | 11-15 01:46:23 | SUCCESS nonebot >> Succeeded to load plugin "rss_rsshub" from "ATRI.plugins.rss.rss_rsshub"
ATRI | 11-15 01:46:23 | SUCCESS nonebot >> Succeeded to load plugin "rss_mikanan" from "ATRI.plugins.rss.rss_mikanan"
ATRI | 11-15 01:46:24 | SUCCESS nonebot >> Succeeded to load plugin "nonebot_plugin_gocqhttp"
ATRI | 11-15 01:46:27 | SUCCESS nonebot >> Running NoneBot...
ATRI | 11-15 01:46:27 | INFO ATRI >> 正在初始化数据库...
ATRI | 11-15 01:46:28 | SUCCESS ATRI >> 数据库初始化完成
ATRI | 11-15 01:46:28 | INFO ATRI >> 当前版本: YHN-001-A07
ATRI | 11-15 01:46:28 | INFO ATRI >> 开始检查更新...
ATRI | 11-15 01:46:28 | ERROR ATRI >> 获取最新推送信息失败...
ATRI | 11-15 01:46:28 | ERROR ATRI >> 获取发布列表失败...
ATRI | 11-15 01:46:28 | INFO ATRI >> 定时任务已启用
ATRI | 11-15 01:46:28 | INFO ATRI >> アトリは、高性能ですから！
ATRI | 11-15 01:46:28 | WARNING polaroid >> 插件 polaroid 缺少所需资源，装载中
ATRI | 11-15 01:46:28 | ERROR polaroid >> 插件 polaroid 装载资源失败. 已自动禁用
ATRI | 11-15 01:46:28 | SUCCESS polaroid >> 插件 polaroid 装载资源完成
ATRI | 11-15 01:46:28 | WARNING geoip >> 插件 IP查询 所需的设置未配置, 将被全局禁用, 填写后请手动启用
ATRI | 11-15 01:46:28 | WARNING setu >> 插件 setu 缺少资源, 装载中...
ATRI | 11-15 01:46:28 | ERROR setu >> 插件 setu 装载资源失败, 命令 '/nsfw' 将失效
ATRI | 11-15 01:46:28 | SUCCESS setu >> 插件 setu 装载资源完成
ATRI | 11-15 01:46:28 | WARNING twitter >> 无法连接至 Twitter，这将导致相关插件无法工作. 已自动禁用.
ATRI | 11-15 01:46:28 | WARNING manage >> 刷新 Nonebot 商店失败, 尝试下一个链接
ATRI | 11-15 01:46:28 | WARNING manage >> 刷新 Nonebot 商店失败, 尝试下一个链接
ATRI | 11-15 01:46:28 | WARNING manage >> 刷新 Nonebot 商店失败, 尝试下一个链接
ATRI | 11-15 01:46:28 | WARNING manage >> 刷新 Nonebot 商店失败, 尝试下一个链接
ATRI | 11-15 01:46:28 | WARNING manage >> 刷新 Nonebot 商店失败, 尝试下一个链接
ATRI | 11-15 01:46:28 | WARNING anti_effort >> 插件 anti_effort 缺少所需资源，装载中
ATRI | 11-15 01:46:28 | ERROR anti_effort >> 插件 anti_effort 装载资源失败. 已自动禁用
ATRI | 11-15 01:46:28 | SUCCESS anti_effort >> 插件 anti_effort 装载资源完成
ATRI | 11-15 01:46:29 | ERROR gocqhttp >> An error has been caught in function 'startup', process 'MainProcess' (27784), thread 'MainThread' (22056):
Traceback (most recent call last):

  File "E:\ARTI\ATRI-main\main.py", line 9, in <module>
    ATRI.run()
    │    └ <function run at 0x00000291CCEAC3A0>
    └ <module 'ATRI' from 'E:\\ARTI\\ATRI-main\\ATRI\\__init__.py'>

  File "E:\ARTI\ATRI-main\ATRI\__init__.py", line 36, in run
    nonebot.run(log_level=log_level)
    │       │             └ 'warning'
    │       └ <function run at 0x00000291CC74ED40>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\atri-N95rEmqc-py3.10\\lib\\si...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'log_level': 'warning'}
    │                 └ ()
    └ <function get_driver at 0x00000291CC74F1C0>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
    │       └ <function run at 0x00000291CCFE2830>
    └ <module 'uvicorn' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\atri-N95rEmqc-py3.10\\lib\\si...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
    │      └ <function Server.run at 0x00000291CCFE29E0>
    └ <uvicorn.server.Server object at 0x00000291FF902BC0>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x00000291CCFE2A70>
           │       │   └ <uvicorn.server.Server object at 0x00000291FF902BC0>
           │       └ <function run at 0x00000291CA497130>
           └ <module 'asyncio' from 'E:\\python310\\lib\\asyncio\\__init__.py'>

  File "E:\python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x00000291FF532880>
           │    └ <function BaseEventLoop.run_until_complete at 0x00000291CA598E50>
           └ <ProactorEventLoop running=True closed=False debug=False>

  File "E:\python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000291CC1E15A0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "E:\python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "E:\python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000291CA59A8C0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "E:\python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000291CA53A290>
    └ <Handle <TaskStepMethWrapper object at 0x00000291FFA8EC80>()>

  File "E:\python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x00000291FFA8EC80>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x00000291FFA8EC80>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x00000291FFA8EC80>()>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\uvicorn\lifespan\on.py", line 88, in main
    await app(scope, self.receive, self.send)
          │   │      │    │        │    └ <function LifespanOn.send at 0x00000291FF9603A0>
          │   │      │    │        └ <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>
          │   │      │    └ <function LifespanOn.receive at 0x00000291FF960430>
          │   │      └ <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>
          │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x00000291FF6AC7F0>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>>
                 │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>>
                 │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
                 │    └ <fastapi.applications.FastAPI object at 0x00000291CD273F70>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x00000291FF6AC7F0>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>>
                           │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>>
                           └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>>
          │    │                │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>>
          │    │                └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x00000291FF9B03D0>
          └ <fastapi.applications.FastAPI object at 0x00000291CD273F70>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>>
          │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>>
          │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x00000291FF9B0400>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x00000291FF9B03D0>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\starlette\middleware\exceptions.py", line 55, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>>
          │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>>
          │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x00000291FF9B0460>
          └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x00000291FF9B0400>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>>
          │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>>
          │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <fastapi.routing.APIRouter object at 0x00000291CD2A40A0>
          └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x00000291FF9B0460>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\starlette\routing.py", line 707, in __call__
    await self.lifespan(scope, receive, send)
          │    │        │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>>
          │    │        │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x00000291FF903130>>
          │    │        └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <function Router.lifespan at 0x00000291CD2680D0>
          └ <fastapi.routing.APIRouter object at 0x00000291CD2A40A0>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
               │    │                └ <fastapi.applications.FastAPI object at 0x00000291CD273F70>
               │    └ <bound method Driver._lifespan_manager of Driver(type='fastapi', adapters=1, bots=0)>
               └ <fastapi.routing.APIRouter object at 0x00000291CD2A40A0>

  File "E:\python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
                       │    └ <async_generator object Driver._lifespan_manager at 0x00000291FF94AE40>
                       └ <contextlib._AsyncGeneratorContextManager object at 0x00000291FF9B0490>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 165, in _lifespan_manager
    await self._lifespan.startup()
          │    │         └ <function Lifespan.startup at 0x00000291CCEACA60>
          │    └ <nonebot.drivers._lifespan.Lifespan object at 0x00000291C9BBBD30>
          └ Driver(type='fastapi', adapters=1, bots=0)

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\nonebot\drivers\_lifespan.py", line 35, in startup
    await self._run_lifespan_func(self._startup_funcs)
          │    │                  │    └ [<function startup at 0x00000291CD28DD80>, <function init_listener at 0x00000291CE2EBAC0>, <function init_source at 0x0000029...
          │    │                  └ <nonebot.drivers._lifespan.Lifespan object at 0x00000291C9BBBD30>
          │    └ <staticmethod(<function Lifespan._run_lifespan_func at 0x00000291CCEAC9D0>)>
          └ <nonebot.drivers._lifespan.Lifespan object at 0x00000291C9BBBD30>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\nonebot\drivers\_lifespan.py", line 29, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
          │    │                    └ <function startup at 0x00000291FF68EF80>
          │    └ typing.Callable[[], typing.Awaitable[typing.Any]]
          └ <function cast at 0x00000291CA333370>

> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\nonebot_plugin_gocqhttp\__init__.py", line 40, in startup
    await download_gocq()
          └ <function download_gocq at 0x00000291FF6FD2D0>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\nonebot_plugin_gocqhttp\process\download.py", line 107, in download_gocq
    url = await get_fastest_mirror(client)
                │                  └ <httpx.AsyncClient object at 0x00000291FFA3D4E0>
                └ <function get_fastest_mirror at 0x00000291FF6A4B80>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\nonebot_plugin_gocqhttp\process\download.py", line 91, in get_fastest_mirror
    assert lowest_latency and fastest_url, "No download domain available."
           │                  └ None
           └ None

AssertionError: No download domain available.
ATRI | 11-15 01:46:29 | ERROR uvicorn >> Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "E:\python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 165, in _lifespan_manager
    await self._lifespan.startup()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\nonebot\drivers\_lifespan.py", line 35, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\nonebot\drivers\_lifespan.py", line 29, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\nonebot_plugin_gocqhttp\__init__.py", line 40, in startup
    await download_gocq()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\loguru\_logger.py", line 1212, in catch_wrapper
    return await function(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\nonebot_plugin_gocqhttp\process\download.py", line 107, in download_gocq
    url = await get_fastest_mirror(client)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\atri-N95rEmqc-py3.10\lib\site-packages\nonebot_plugin_gocqhttp\process\download.py", line 91, in get_fastest_mirror
    assert lowest_latency and fastest_url, "No download domain available."
AssertionError: No download domain available.

ATRI | 11-15 01:46:29 | ERROR uvicorn >> Application startup failed. Exiting.

**Comment by Kyomotoi** [comment]
具体报错信息为：
```
AssertionError: No download domain available.
```
通常是网络原因造成的，可以多试几次，或者在 `config.yml` 中，把有关 **go-cqhttp** 的设置中的 `enabled` 改为 `false`，然后自行处理协议端（类似gocq的实现）连接至ATRI

**Comment by na-neko** [comment]
@Kyomotoi 成功解决了，但在QQ聊天上出现了新的问题
![Uploading 7.png…]()

**Comment by na-neko** [comment]
@Kyomotoi 已经解决，但在QQ聊天上出现了新的问题
![7](https://github.com/user-attachments/assets/7f5f2e8f-4a53-4aaf-8a61-690abee4ce2d)
