### ISSUE TITLE
变量传递无需定义函数

### ISSUE THREAD

**Issue by sdy623** [Kyomotoi/ATRI#12]
`e = "" 
def BAIDU_SECRET():
    return e`
如上 为什么传递变量需要定义函数

下面是无需定义函数即可在.py文件间传递的实例
`JUHE_JOKE_API_KEY = ''  # 笑话大全
JUHE_IDIOM_API_KEY = ''  # 成语词典`

**Comment by Kyomotoi** [comment]
因为在此之前并没在vscode中打开相关项目文件，导致报错，这里疏忽了，抱歉
下星期预计使用yml文件进行相关的配置操作

**Comment by Kyomotoi** [comment]
现master分支的config已使用json进行加载，久等叻
