### ISSUE TITLE
关于新功能征集

### ISSUE THREAD

**Issue by Kyomotoi** [Kyomotoi/ATRI#13]
最近事太多没来得及构思新的功能，现征集所有想法！
无论您是否会编程，都可以提出！（可能不会回复但会考虑）
格式：
- 功能名：
- 目的：
- 实现方法（可选）：

**Comment by Yiwen-Chan** [comment]
- 功能名：申请头衔xxx
- 目的：若atri为群主，群员可自定义申请头衔
- 实现方法（可选）：

**Comment by opensourcefuture** [comment]
重新支持mirai(x)

**Comment by Kyomotoi** [comment]
> 重新支持mirai(x)

项目推荐的 go-cqhttp 就是 go-mirai + CQHTTP，如果想运行其他 mirai 插件的话，可以选择 mirai 官方库里的 或者 miraiok 以及各大佬的其他语言实现的 mirai，然后装上 CQHTTP 插件即可，这样就既可以运行本项目也可以运行其他mirai插件xd

**Comment by opensourcefuture** [comment]
> > 重新支持mirai(x)
> 
> 项目推荐的 go-cqhttp 就是 go-mirai + CQHTTP，如果想运行其他 mirai 插件的话，可以选择 mirai 官方库里的 或者 miraiok 以及各大佬的其他语言实现的 mirai，然后装上 CQHTTP 插件即可，这样就既可以运行本项目也可以运行其他mirai插件xd

明白了，这就使用mirai-cqhttp

**Comment by JACK-CLDS** [comment]
功能：图片生成 比如喜报悲报 条幅
目的：生成就方便多了 也可以从网络上找api直接用

功能：网页转到群文件pdf或者图片
目的：群内疑难解答直接参考

**Comment by sudo0m** [comment]
功能：聊天
目的：使用GPT-2实现了在聊天过程中的短对话生成，效果请看链接
实现方法：[利用GPT-2制作聊天机器人](https://mirai.mamoe.net/topic/497/%E5%88%A9%E7%94%A8gpt-2%E5%88%B6%E4%BD%9C%E8%81%8A%E5%A4%A9%E6%9C%BA%E5%99%A8%E4%BA%BA)
