### ISSUE TITLE
关于舆情

### ISSUE THREAD

**Issue by zyc14588** [Kyomotoi/ATRI#18]
兄弟，你这舆情部分看得我血压拉满，做舆情不上NLP，真的是太暴殄天物了，哪怕是接入openNLP平台呢？脑壳疼

**Comment by Kyomotoi** [comment]
抱歉，这部分还没做完，目前是打算正则匹配，或者for i in将关键词扔到信息内判定是否存在

**Comment by Kyomotoi** [comment]
其实这个舆情判断，实际上是判定接受的消息是否包含设定的关键词，然后做出回应

**Comment by zyc14588** [comment]
关键词过滤呀，不考虑引入NLP做自学习型舆情监控吗？关键词库可是会随着时间慢慢变得很庞大的

**Comment by Kyomotoi** [comment]
这么一说确实，感谢提供建议！
之前傻傻考虑正则又考虑for i in最后扯到效率上导致琢磨不定
