### ISSUE TITLE
关于if开关失灵问题

### ISSUE THREAD

**Issue by Kyomotoi** [Kyomotoi/ATRI#2]
在近日测试中发现：
一个或几个py文件中写有的if空置某command开启或关闭的功能，使其中一个启用或关闭后，其他的if会失效，不受控制，目前有待解决，如果有更好的方法欢迎继续提交issues，感谢！

**Comment by mnixry** [comment]
具体代码是哪几段？我康康

**Comment by Kyomotoi** [comment]
> 具体代码是哪几段？我康康

嘛就setu.py的第一个on_command
然后session.ctx似乎还能用，就没改（
之前一直这样做的开关
