### ISSUE TITLE
？无法启动

### ISSUE THREAD

**Issue by Thomitics** [Kyomotoi/ATRI#31]
![Windows PowerShell 180223](https://user-images.githubusercontent.com/62173814/123408517-abb32600-d5df-11eb-9b9b-20e254a6f4b4.png)
这之后就卡住了，无法启动

**Comment by Thomitics** [comment]
CQhttp已经启动了

**Comment by Kyomotoi** [comment]
你可以先加入讨论群（Q Q），让群友帮你解答一下，我这边暂时没有空闲时间 非常抱歉（x
群号：567297659
