### ISSUE TITLE
色图API是不是应该更新一下啊

### ISSUE THREAD

**Issue by Thomitics** [Kyomotoi/ATRI#34]
>目前已将 API 迁移出我个人的服务器并转用某些白嫖服务，因此我将限制放开了，不再需要 apikey 并且一次允许返回的数量增加了，但这也意味着可能存在一些来自服务商的隐性限制

**Comment by Kyomotoi** [comment]
新的插件在重构了，最近不会更新老的，有能力的可以自行改改。还有，最近建议别法涩图了，小心号没

**Comment by Kyomotoi** [comment]
请查看最新commit
