### ISSUE TITLE
《背叛自己》

### ISSUE THREAD

**Issue by 2096779623** [Kyomotoi/ATRI#39]
![](https://s2.loli.net/2022/01/11/HJUI2MQADT3wChr.png)

**Comment by Kyomotoi** [comment]
请问：这是被对方魔改过？还是人机一体

如果是被对方魔改过（源码，词库一类不算）
可以根据[GPLv3](https://www.gnu.org/licenses/gpl-3.0.html)协议要求对方公开修改过的版本

你可以尝试at bot发送`关于`，以查看其返回是否包含该项目的url

如果为人机一体：当个乐就好（
