### ISSUE TITLE
关于拓展插件服务控制的疑问

### ISSUE THREAD

**Issue by marswh12312313** [Kyomotoi/ATRI#41]
是否有办法能够将服务控制应用于第三方插件？

**Comment by marswh12312313** [comment]
现在我感觉好像只能改第三方插件的代码

**Comment by Kyomotoi** [comment]
本项目与第三方插件不同的是:
  - 本项目的 `matcher` 是重新封装过的，且需要 `rule` 判断其是否启用
  - 第三方使用的 `matcher` 是 `nonebot2` 包本身的，且不附带检测其是否启用的 `rule`

* `matcher`: 可以理解为触发器。

综上，不能用于第三方，除非像你所说的更改第三方插件的代码

**Comment by marswh12312313** [comment]
好的，那我去修改代码。。

**Comment by marswh12312313** [comment]
改了几个，发现可以总结一个方法了
