### ISSUE TITLE
插件 `b站订阅助手` 存在bug，修复进行中

### ISSUE THREAD

**Issue by Kyomotoi** [Kyomotoi/ATRI#45]
经过个别群友上机测试
发现如下问题:

1. 会依次发送所拿到的动态信息，导致刷屏。原因可能是`时间对比`出错
2. 禁用该插件无法阻止其继续发送属于本插件的消息。原因是`业务逻辑部分未适配对应的功能开关检测`

修复前，你可以选择:

1. 暂时不启用此插件
2. 将插件相关文件删除

**Comment by Yuki-Asuuna** [comment]
关于第一个问题的修复方案是：插入订阅的时候，以当前的时间作为更新时间；原先的更新时间默认是1970-01-01，所以会导致对于一个up拿出10条左右的动态信息。
关于第二个问题确实是没有考虑到，功能检测这一块我再看看。
