### ISSUE TITLE
404 site not found error

### ISSUE THREAD

**Issue by aimerneige** [Kyomotoi/ATRI#5]
You Blog has been 404.
Please fix it.
I can't see the help doc.

**Comment by Kyomotoi** [comment]
SORRY!
Now is change.
The blog is so old because my bot is not done.
I will update it when my bot is done!

**Comment by aimerneige** [comment]
Thanks for your replay.
Sorry for using English.
I do not have Chinese input on Linux.

**Comment by Kyomotoi** [comment]
ITS OKAY~
(｡･∀･)ﾉﾞ
