### ISSUE TITLE
部署卡住

### ISSUE THREAD

**Issue by W4J1e** [Kyomotoi/ATRI#51]
亲爱的开发者，
我也想部署一个可可爱爱的ATRI，可是我在 debian 上从昨晚折腾到了现在，期间出现的报错我都尽可能通过搜索引擎解决或排除了。
现在运行 `sudo docker-compose up`会一直一直卡在某一个步骤。
运行之初的输出：
![33](https://user-images.githubusercontent.com/74824162/167558202-0ccec94a-67e6-45c7-a42b-742c9b001324.jpg)
运行十几分钟后的输出：
![22](https://user-images.githubusercontent.com/74824162/167558669-41d2a3ce-3a5a-4d55-a4fc-00ab228e7499.jpg)

除了用 docker 的方法之外，我也试过 linux 的方法，在输出一长串很多很多信息之后，最后提示启动失败。
配置文件里`download_domain`留空、更换python镜像源、更新python版本我都尝试过了。请指教。
如果有需要补充的内容烦请告知，谢谢。

**Comment by Kyomotoi** [comment]
很抱歉让你等待了这么久
请问 debian 的版本是？看起来是库出现了问题

**Comment by Kyomotoi** [comment]
由于长时间未回复，此 issue 将被关闭，如有其它疑问，可以加入群聊一同讨论
👉[传送门](https://jq.qq.com/?_wv=1027&k=q2PYqZTO)

**Comment by W4J1e** [comment]
> 很抱歉让你等待了这么久
> 请问 debian 的版本是？看起来是库出现了问题

抱歉，之前忙忘了。版本是：
Debian GNU/Linux 11 x86_64(Py3.7.9)

**Comment by Kyomotoi** [comment]
请问你的服务器是腾讯云一类的大厂，还是挂机宝一类

提供系统信息还是建议使用诸如:
neofetch, screenfetch

然后截图

**Comment by W4J1e** [comment]
debian系统信息：
![Uploading 屏幕截图 2022-05-18 123053.jpg…]()
linux启动输出截图：
![e1](https://user-images.githubusercontent.com/74824162/168958156-cdb47963-598e-494f-ae6c-262b8676c901.jpg)
![e2](https://user-images.githubusercontent.com/74824162/168958192-a69a8bfa-7d17-4de5-87a5-c6897bd8879b.jpg)
![e3](https://user-images.githubusercontent.com/74824162/168958198-daf97d9e-19b9-4c4b-a2fd-538c8e662e5d.jpg)
![e4](https://user-images.githubusercontent.com/74824162/168958204-58dbf58b-2e89-45e4-a47a-10de51ead7be.jpg)
![e5](https://user-images.githubusercontent.com/74824162/168958209-f098021c-9035-4a0b-b146-a163caa79922.jpg)
![e6](https://user-images.githubusercontent.com/74824162/168958213-ce3978b1-c9a4-4619-a268-15c5060390c9.jpg)
![e7](https://user-images.githubusercontent.com/74824162/168958216-c056bd75-ac7b-4d2f-aae5-7d615022c69f.jpg)

**Comment by Kyomotoi** [comment]
大概知道问题了（
修复之前的解决方法是禁用 ’内置gocq’，转而使用外部的，或者使用默认配置：github.com

**Comment by W4J1e** [comment]
> 大概知道问题了（
> 
> 修复之前的解决方法是禁用 `内置gocq`，转而使用外部的。
> 
> 或者使用默认配置：github.com

了解了，我回头试试，谢谢。

**Comment by Kyomotoi** [comment]
该bug为依赖包 `httpx` 所导致，目前解决办法就是等他们修复、发新版
