### ISSUE TITLE
关于部署时的报错

### ISSUE THREAD

**Issue by Shimakazelewis** [Kyomotoi/ATRI#52]
![image](https://user-images.githubusercontent.com/99003751/169193084-c6862f92-8a90-4552-8db0-8099a5d9fc5d.png)
部署的时候出现了这个问题，没有动过代码，大佬们这个应该怎么解决QAQ

**Comment by Kyomotoi** [comment]
请尝试将设置 `InlineGoCQHTTP` 下的 `download_domain` 恢复原状: `github.com`

**Comment by 3091977221** [comment]
![Uploading Screenshot_20220522_210358_com.termux.jpg…]()
在进行 pip install -r requirements.txt  出现的报错

**Comment by Kyomotoi** [comment]
相关依赖: `httpx` 已修复此bug，请尝试更新依赖.
