### ISSUE TITLE
如何单独将 ATRI 的一些插件添加到其它 bot 中使用？

### ISSUE THREAD

**Issue by NoNormalCreeper** [Kyomotoi/ATRI#53]
### 描述问题 | Describe the question

如题，因为 ATRI 实在是太可爱了，但我又有自己的 bot，所以我想**将该项目的一部分插件为我自己所用**。

### 补充内容 | Additional context

故我将这些插件的文件夹加入到我自己的 bot 的 `src/plugins` 目录下，却发现无法正常使用。

我又在此基础上将您项目中的 `ATRI` 文件夹添加到了我 bot 的 **根目录 与 `src/plugins` 目录**下，虽然可以勉强运行，但仍存在许多问题，如“老婆”功能意外阻断了我原有的插件、“以图搜番”功能无法正常使用、“涩图嗅探”功能无法正常使用、`enssial.py` 内的功能无法正常调用等等。我查阅了文档，但没有相关的介绍。

我的 bot 项目为 NoNormalCreeper/Kori-Bot ，您可以在[此处](https://github.com/NoNormalCreeper/Kori-Bot/tree/dev)详细查看我的目录结构。

---
希望您能在百忙之中 `牺牲打游戏的时间来帮助我` 一下，非常感谢您的指导！

**Comment by Kyomotoi** [comment]
抱歉，准备高考了

推荐你加入我们的群聊同群友一起讨论👉 [传送门](https://jq.qq.com/?_wv=1027&k=jhTkpWLi)

**Comment by NoNormalCreeper** [comment]
好的，谢谢。

🎉 祝高考顺利！ 🎉

**Comment by Kyomotoi** [comment]
由于此 Issue 长久没人回复，认为已解决相关问题，此 Issue 将被关闭.

**Comment by NoNormalCreeper** [comment]
未解决问题，仍需要帮助（
