### ISSUE TITLE
未知错误->连接超时

### ISSUE THREAD

**Issue by HA-JD** [Kyomotoi/ATRI#55]
{
    "track_id": "rpsPw1hc",
    "prompt": "Unknown ERROR->ConnectTimeout",
    "time": "2022-06-08 19:42:49",
    "content": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpcore\\backends\\asyncio.py\", line 101, in connect_tcp\n    stream: anyio.abc.ByteStream = await anyio.connect_tcp(\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\anyio\\_core\\_sockets.py\", line 218, in connect_tcp\n    await event.wait()\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 662, in __aexit__\n    raise exceptions[0]\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\anyio\\_core\\_sockets.py\", line 164, in try_connect\n    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1691, in connect_tcp\n    await get_running_loop().create_connection(\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 1041, in create_connection\n    sock = await self._connect_sock(\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 955, in _connect_sock\n    await self.sock_connect(sock, address)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\proactor_events.py\", line 702, in sock_connect\n    return await self._proactor.connect(sock, address)\nasyncio.exceptions.CancelledError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpcore\\_exceptions.py\", line 8, in map_exceptions\n    yield\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpcore\\backends\\asyncio.py\", line 101, in connect_tcp\n    stream: anyio.abc.ByteStream = await anyio.connect_tcp(\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\anyio\\_core\\_tasks.py\", line 118, in __exit__\n    raise TimeoutError\nTimeoutError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpx\\_transports\\default.py\", line 60, in map_httpcore_exceptions\n    yield\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpx\\_transports\\default.py\", line 353, in handle_async_request\n    resp = await self._pool.handle_async_request(req)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 253, in handle_async_request\n    raise exc\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 237, in handle_async_request\n    response = await connection.handle_async_request(request)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpcore\\_async\\connection.py\", line 86, in handle_async_request\n    raise exc\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpcore\\_async\\connection.py\", line 63, in handle_async_request\n    stream = await self._connect(request)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpcore\\_async\\connection.py\", line 111, in _connect\n    stream = await self._network_backend.connect_tcp(**kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpcore\\backends\\auto.py\", line 23, in connect_tcp\n    return await self._backend.connect_tcp(\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpcore\\backends\\asyncio.py\", line 101, in connect_tcp\n    stream: anyio.abc.ByteStream = await anyio.connect_tcp(\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\contextlib.py\", line 137, in __exit__\n    self.gen.throw(typ, value, traceback)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpcore\\_exceptions.py\", line 12, in map_exceptions\n    raise to_exc(exc)\nhttpcore.ConnectTimeout\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ATRI-main\\ATRI\\exceptions.py\", line 98, in _track_error\n    raise exception\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\message.py\", line 196, in _run_matcher\n    await matcher.run(bot, event, state, stack, dependency_cache)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\internal\\matcher.py\", line 668, in run\n    await self.simple_run(bot, event, state, stack, dependency_cache)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\internal\\matcher.py\", line 635, in simple_run\n    await handler(\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\dependencies\\__init__.py\", line 92, in __call__\n    return await self.call(**values)\n  File \"C:\\Users\\Administrator\\Desktop\\ATRI-main\\ATRI\\plugins\\kimo\\__init__.py\", line 22, in _chat\n    repo = await Kimo().deal(msg, user_id)\n  File \"C:\\Users\\Administrator\\Desktop\\ATRI-main\\ATRI\\plugins\\kimo\\data_source.py\", line 112, in deal\n    data = await cls._load_data()\n  File \"C:\\Users\\Administrator\\Desktop\\ATRI-main\\ATRI\\plugins\\kimo\\data_source.py\", line 50, in _load_data\n    await cls._generate_data()\n  File \"C:\\Users\\Administrator\\Desktop\\ATRI-main\\ATRI\\plugins\\kimo\\data_source.py\", line 37, in _generate_data\n    data = await cls._request(KIMO_URL)\n  File \"C:\\Users\\Administrator\\Desktop\\ATRI-main\\ATRI\\plugins\\kimo\\data_source.py\", line 27, in _request\n    res = await request.get(url)\n  File \"C:\\Users\\Administrator\\Desktop\\ATRI-main\\ATRI\\utils\\request.py\", line 15, in get\n    return await client.get(url, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpx\\_client.py\", line 1729, in get\n    return await self.request(\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpx\\_client.py\", line 1506, in request\n    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpx\\_client.py\", line 1593, in send\n    response = await self._send_handling_auth(\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpx\\_client.py\", line 1621, in _send_handling_auth\n    response = await self._send_handling_redirects(\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpx\\_client.py\", line 1658, in _send_handling_redirects\n    response = await self._send_single_request(request)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpx\\_client.py\", line 1695, in _send_single_request\n    response = await transport.handle_async_request(request)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpx\\_transports\\default.py\", line 353, in handle_async_request\n    resp = await self._pool.handle_async_request(req)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\contextlib.py\", line 137, in __exit__\n    self.gen.throw(typ, value, traceback)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\httpx\\_transports\\default.py\", line 77, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\nhttpx.ConnectTimeout\n"
}

**Comment by Kyomotoi** [comment]
请尝试挂上代理或者使用国外服务器进行部署

还有请按照模板发起 Issue

**Comment by HA-JD** [comment]
en.已经好了，打扰了
