### ISSUE TITLE
/app/ATRI/plugins/console/driver/__init__.py中driver未定义

### ISSUE THREAD

**Issue by dovela** [Kyomotoi/ATRI#56]
**描述错误 | Describe the bug**
之前装在本机上，今天刚换的docker版，
 /app/ATRI/plugins/console/driver/__init__.py 有错误，看了下commit，是否和最近的更新有关？

**如何复现 | To Reproduce**
告诉我们该错误是如何触发的:
执行`docker-compose up`后就这样了，docker-compose.yml 和 comfig.yml 已配置

**截图 | Screenshots**
![image](https://user-images.githubusercontent.com/33590269/173501174-f9c80e8e-498e-4bcf-82a1-4baf1b3aa216.png)

**操作环境 | Desktop:**
 - OS: omv6.0（基于debian11）
 - Platform Info: i5-7200u 4g
 - ATRI Version: [e.g. YHN-001-A05.fix1]
 - Runtime Area: CN

**Comment by Kyomotoi** [comment]
感谢反馈错误. 此段为优化代码时的疏忽.

[最新 commit](https://github.com/Kyomotoi/ATRI/commit/96f7354358752fc938ae20425fb5f2c3c7750883) 已修复.

**Comment by Kyomotoi** [comment]
刚才的bug未完全修复，目前最新 commit已完成修复，还请重新clone
