### ISSUE TITLE
文档里有一处拼写错误

### ISSUE THREAD

**Issue by RMSCA** [Kyomotoi/ATRI#57]
**描述错误 | Describe the bug**

这个地方的 `requirements.txt` 拼错了
![image](https://user-images.githubusercontent.com/72942610/179124699-cc1b5369-7205-452e-a384-4736aa9f059f.png)

**如何复现 | To Reproduce**
https://atri.imki.moe/install/install-direct/

**Comment by Kyomotoi** [comment]
感谢提交 Issue, 此 Issue 已于文档最近一次commit修复.
