### ISSUE TITLE
希望能导入nonebot插件

### ISSUE THREAD

**Issue by beiyaohhhc** [Kyomotoi/ATRI#58]
**描述你的大致想法 | Describe your idea**
希望能导入nonebot上的插件
**描述你想要的解决方案 | Describe the solution you'd like**
无
**操作环境 | Desktop:**
 - OS:windows 2012
 - Platform Info:2c2g 60g
 - Runtime Area:HongKong

**补充内容 | Additional context**
你可以在此添加其它说明，或向我们提供你的解决方案.

**Comment by Kyomotoi** [comment]
感谢提交, 已提上日程.

**Comment by 1103859909** [comment]
有没有使用菜单什么的  感觉功能都是需要开启的嘛  怎么开

**Comment by Kyomotoi** [comment]
> 有没有使用菜单什么的 感觉功能都是需要开启的嘛 怎么开

就此问题请重新开一个新的 issue 而不是在不相关的 issue 下发起提问. 顺便回答一下, "新手教程" 已经提上日程了, 还请多等等.

**Comment by 1103859909** [comment]
好的  谢谢

**Comment by Kyomotoi** [comment]
该功能现已支持，相关 [commit](https://github.com/Kyomotoi/ATRI/commit/bb52f7b70dd3b5def1a938fbbc3c0ee08ea3a77c)
文档帮助会在稍后补上，你可以通过bot内查询：管理
