### ISSUE TITLE
机器人回复不会自动触发吗？

### ISSUE THREAD

**Issue by 1409109991** [Kyomotoi/ATRI#59]
![image](https://user-images.githubusercontent.com/79674967/188620161-7ea12e0a-9d8f-4709-a8c7-9429a963c681.png)
输入机器人名字不会自动触发回复插件吗？

**Comment by 1409109991** [comment]
必须要at吗？

**Comment by Kyomotoi** [comment]
无论 at 与否, 空 at bot 而不发送任何信息都不会得到回复. 图中 bot 的反应为 plugins/wife 下的功能, 为主动触发, 时间间隔为 10min.
后续会将该功能改为上述所说: at 后有所反应
