### ISSUE TITLE
开启和关闭功能不可用

### ISSUE THREAD

**Issue by Sylive147** [Kyomotoi/ATRI#6]
switch.json似乎在switch.py后没变动撒。
目前通过文本编辑达到目的awa。

**Comment by Kyomotoi** [comment]
请问能否提供开关功能段的运行log

**Comment by Sylive147** [comment]
不知道log存在哪里耶&nbsp;
我从这里翻源码找到json然后发现没变的


Sylive_147
sylive_147@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kyomotoi/ATRI"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月16日(星期天) 下午5:56
收件人:&nbsp;"Kyomotoi/ATRI"<ATRI@noreply.github.com&gt;;
抄送:&nbsp;"_chaostaR"<771443068@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kyomotoi/ATRI] 开启和关闭功能不可用 (#6)





 
请问能否提供开关功能段的运行log

**Comment by Kyomotoi** [comment]
先在群内运行开关插件的命令，然后截图一下后端带相关关键字的就行

**Comment by Sylive147** [comment]
刚才好像发错了图没出来）
![image](https://user-images.githubusercontent.com/60504440/90331914-effe8e80-dfea-11ea-99f3-8e7aa463c193.png)
后端是BOT那个吗

**Comment by Kyomotoi** [comment]
开关的Bug已修复，对触发命令和被操作插件名做出了一些修改，详细请见使用文档
clone仓库然后删除旧的plugins文件夹，粘上新的plugins文件夹即可
