### ISSUE TITLE
所以说，这机器人改怎么用

### ISSUE THREAD

**Issue by 1103859909** [Kyomotoi/ATRI#60]
所以说，这机器人改怎么用，除了会冷不丁的冒出来跟我贴贴以为其他功能一个也用不了（苦恼）
[截图.zip](https://github.com/Kyomotoi/ATRI/files/9534862/default.zip)

**Comment by Klop233** [comment]
https://project-atri-docs.vercel.app/

**Comment by 1103859909** [comment]
![无标题](https://user-images.githubusercontent.com/107859647/189337362-daf34e1f-3549-4396-8f2a-d92456d91f19.png)

**Comment by Klop233** [comment]
https://project-atri-docs.vercel.app/user/overview/
这里也有
