### ISSUE TITLE
希望涩图嗅探去除对gif类型的支持或提供开关

### ISSUE THREAD

**Issue by tszjj** [Kyomotoi/ATRI#69]
**描述你的大致想法 | Describe your idea**
涩图嗅探功能对gif类型的图片识别误差明显偏大, 即使将阈值调整为80%也依然有大量误触发

**描述你想要的解决方案 | Describe the solution you'd like**
希望涩图嗅探去除对gif类型的支持或提供开关

**Comment by Kyomotoi** [comment]
相关功能现已支持，文档帮助稍后更新，现你可以通过bot内的帮助查询相应命令
