### ISSUE TITLE
WorldCloud

### ISSUE THREAD

**Issue by Sylive147** [Kyomotoi/ATRI#7]
![image](https://user-images.githubusercontent.com/60504440/90374517-34029980-e0a6-11ea-92bb-86b0e22bfb71.png)
(关键词写漏了？
![image](https://user-images.githubusercontent.com/60504440/90374720-8348ca00-e0a6-11ea-8e87-625e2e447ff2.png)

**Comment by Kyomotoi** [comment]
![A@`_P`LRZFS`VUPWHXY3}VF](https://user-images.githubusercontent.com/37587870/90374982-e76b8e00-e0a6-11ea-8dd2-eb0966801c0c.png)
请检查空格...
