### ISSUE TITLE
检查资源消耗异常 一直重复报

### ISSUE THREAD

**Issue by YouYouLip** [Kyomotoi/ATRI#73]
![610@AIL`5 XG{A2XQ RHTR9](https://user-images.githubusercontent.com/119958263/209762541-0bbf6440-36a5-4355-9170-bd4b27ab3fec.png)
说实话这个检查资源消耗异常。。。 并没有异常 只不过是我的硬盘快满了
![3E3 KO_V@7909A8T931JPJY](https://user-images.githubusercontent.com/119958263/209762628-af7ce993-b583-48cc-a886-4c58f388b221.png)
然后每隔一段时间就会提醒我 所以我感觉这个检测资源消耗异常的写法可能有点奇怪（？）因为如果是bot造成的硬盘满而导致的资源检查消耗异常我可以觉得很正常 但为什么我下的东西过多导致硬盘满了也能这样 有点怪
![)L`TRON 4Y`A DE%7`9%8IS](https://user-images.githubusercontent.com/119958263/209762875-b3b07d10-3ce1-4754-a3e0-7705cec9bba8.png)
有办法取消自动检查或者添加一个可开启自动检查的情况么

**Comment by YouYouLip** [comment]
这个资源消耗检查有点问题 每隔一段时间给我报
![H{E7Z_U~`8`4Z6MUXD{0 XK](https://user-images.githubusercontent.com/119958263/209763177-19ea2123-099c-4852-bc92-f79581f482e2.png)
显示的是硬盘使用率过高 但其实是我的e盘快满了
![N(7C( A~TZ5JHFP6O7}PMF0](https://user-images.githubusercontent.com/119958263/209763248-3ebd1f61-a927-46f8-9ebc-f4dbb77e6751.png)

**Comment by YouYouLip** [comment]
如果是bot导致的硬盘过满检查资源消耗异常提醒我我觉得很正常 但是如果是用户手动添加文件过多导致的硬盘过满而触发的资源消耗检查异常的话 这我就感觉很怪

**Comment by Kyomotoi** [comment]
此项功能检测的就是 bot 所在的盘占用率
鉴于有许多用户反馈相似问题，将在下午推送一个临时更新

**Comment by YouYouLip** [comment]
> 此项功能检测的就是 bot 所在的盘占用率 鉴于有许多用户反馈相似问题，将在下午推送一个临时更新

嗯嗯 感谢

**Comment by Kyomotoi** [comment]
最近更新已修复
