### ISSUE TITLE
该目标不存在实例

### ISSUE THREAD

**Issue by SHERD1** [Kyomotoi/ATRI#76]
**问题描述**
bot正常启动，但无法进入控制台
私聊bot无反应
token填写无误

**日志截图**
![QQ截图20230130130545](https://user-images.githubusercontent.com/123920739/215392066-ef88d9e4-0c3d-403f-8251-5dd1feae3f7d.png)
![QQ截图20230130130507](https://user-images.githubusercontent.com/123920739/215392345-28e73ec6-be77-4150-a63a-5d249e1c8472.png)
![QQ截图20230130130442](https://user-images.githubusercontent.com/123920739/215392368-51d34dfa-ff92-4046-bf35-814e312a69d1.png)

**Comment by Kyomotoi** [comment]
控制台的 `token` 需启动后向 **bot 私戳索取**
