### ISSUE TITLE
机器人无法启动

### ISSUE THREAD

**Issue by 1103859909** [Kyomotoi/ATRI#77]
![image](https://user-images.githubusercontent.com/107859647/217538322-1d41f644-94ae-4408-9b94-8f05c0b70fff.png)

**Comment by 1103859909** [comment]
依赖什么的也装好了

**Comment by Kyomotoi** [comment]
请检查你的 `config.yml` 中 `WithGoCQHTTP` 部分，账号是否**认真**填写

**Comment by 1103859909** [comment]
oo 不好意思 是我没看教程
