### ISSUE TITLE
使用pipenv构建独立的安装与运行环境

### ISSUE THREAD

**Issue by fatinghenji** [Kyomotoi/ATRI#78]
**描述你的大致想法 | Describe your idea**
我在使用termux作为终端，并且使用的是python3.8.15，这个无法安装poetry。是否可以使用相对来说更易安装的pipenv来构建独立的安装与运行环境呢？

**描述你想要的解决方案 | Describe the solution you'd like**
使用pipenv来构建独立的安装与运行环境，规避无法安装poetry的问题。

**操作环境 | Android**
 - OS: Linux-Termux
 - Platform Info: 8c8g 256g 
 - Runtime Area:Henan~在我手机上跑的~

**补充内容 | Additional context**
> pipenv是基于pip的Python包管理工具，它和pip的用法非常相似，可以看作pip的加强版，它的出现解决了旧的pip+virtualenv+requirements.txt的工作方式的弊端。具体来说，它是pip、Pipfile和Virtualenv的结合体，它让包安装、包依赖管理和虚拟环境管理更加方便，使用它可以实现高效的Python项目开发工作流。

当然`pipenv`也有一些自己存在的问题：
> virtualenv的使用存在一定的问题：
由于跨平台的使用不太一致，有时候处理包之间的依赖总存在问题。
可能需要手动安装/删除某些特定版本的包
存在多个环境（开发环境、测试环境、生产环境）时，依赖包目录文件requirements.txt 会需要存在多个，无比繁琐
要定期更新 requirements.txt，保持项目环境的一致性

但是总归有另一种解决方案~

**Comment by Kyomotoi** [comment]
首先感谢你的分享~
其次针对该平台不打算进行实际解决，你有 blog 的话可以记录相关操作方法，我会在文档给予提示引导有需求的用户到你那查看。

**Comment by fatinghenji** [comment]
能否提供一份`requirements.txt`呢？

**Comment by Kyomotoi** [comment]
在其它能运行 poetry 的平台上，在项目根目录下键入：`poetry export --output requirements.txt`

**Comment by fatinghenji** [comment]
无法安装`onnxruntime`依赖，看来似乎无法在Android上运行。
