### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by Chocominttt** [Kyomotoi/ATRI#86]
**描述错误 | Describe the bug**
使用/con.auth指令报错

呜——出错了...请反馈维护者
来自: 控制台
信息: UnkErr JSONDecodeError
追踪ID: f0eSV9Y7

**如何复现 | To Reproduce**

**错误预期行为 | Expected behavior**
请尽可能地使用简洁语言描述，以方便开发者快速定位重点.

**截图 | Screenshots**
![image](https://user-images.githubusercontent.com/79995876/234172984-d77b3c0e-0836-4419-951b-0fa9c402d4c4.jpeg)

![image](https://user-images.githubusercontent.com/79995876/234173005-2c91820c-9d8a-43db-bcff-974740090609.jpeg)
**操作环境 | Desktop:**
 - OS: ubuntu20.04
 - Platform Info: [e.g. 2c2g 30g (2 core cpu 2g memories 30g storage)]
 - ATRI Version: [e.g. YHN-001-A05.fix1]
 - Runtime Area: [e.g. HongKong]

**补充内容 | Additional context**
你可以在此添加其它说明，或向我们提供你的解决方案.

**Comment by Kyomotoi** [comment]
控制台正进行重构，目前强制禁用，请等待后续更新
